name: Build Pipeline

on:
  workflow_call:
    inputs:
      upload-artifacts:
        description: 'Upload build artifacts'
        required: false
        default: true
        type: boolean
      artifact-name:
        description: 'Name for build artifacts'
        required: false
        default: 'meetingmuse-dist'
        type: string
    outputs:
      build-status:
        description: 'Build status'
        value: ${{ jobs.build.outputs.status }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.build-result.outputs.status }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-py3.13-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-py3.13-

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: make dev-install

    - name: Build package
      run: make build

    - name: Set build status
      id: build-result
      run: echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload build artifacts
      if: inputs.upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          dist/
          !dist/**/*.pyc
        retention-days: 30
